// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcn4RRKeuAIA-bz-5gCLkuk1LuEzOKb48',
    appId: '1:618831949444:web:3417997ea68ea445665cd1',
    messagingSenderId: '618831949444',
    projectId: 'sneakerheadsdb',
    authDomain: 'sneakerheadsdb.firebaseapp.com',
    storageBucket: 'sneakerheadsdb.appspot.com',
    measurementId: 'G-TLGJP7KJPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ24vEUhvSX-B35ibXhVjhCBb4IbCVpHo',
    appId: '1:618831949444:android:e260e5c948f7725d665cd1',
    messagingSenderId: '618831949444',
    projectId: 'sneakerheadsdb',
    storageBucket: 'sneakerheadsdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxOU30OkvCXIfnHk6brFkIYzBPCX-9jc8',
    appId: '1:618831949444:ios:b158cfbf3c48d0bc665cd1',
    messagingSenderId: '618831949444',
    projectId: 'sneakerheadsdb',
    storageBucket: 'sneakerheadsdb.appspot.com',
    iosClientId: '618831949444-d7md9gs1naik1n5apfi3h53tkpt34ju3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakerheads',
  );
}
